/**
 * Created by supun on 10/03/18.
 */
export const REDUX_API_GATEWAY_ACTIONS = {

    //saga action
    API_GATEWAY_FETCHING:'API_GATEWAY_FETCHING',
    API_GATEWAY_FETCH_LATEST:'API_GATEWAY_FETCH_LATEST',
    API_GATEWAY_FETCHING_SUCCESS : 'API_GATEWAY_FETCHING_SUCCESS',
    API_GATEWAY_FETCHING_FAILURE:'API_GATEWAY_FETCHING_FAILURE',
    //pets action
    GET_PETS_SUCCESS:'GET_PETS_SUCCESS',
    GET_PETS_FAILE:'GET_PETS_FAILE',

    //schedulte action
    GET_SCHEDULE_EVENT_SUCCESS:'GET_SCHEDULE_EVENT_SUCCESS',
    GET_SCHEDULE_EVENT_FAILE:'GET_SCHEDULE_EVENT_FAILE',
    POST_SCHEDULE_EVENT_SUCCESS:'POST_SCHEDULE_EVENT_SUCCESS',
    POST_SCHEDULE_EVENT_FAIL:'POST_SCHEDULE_EVENT_FAIL'

};


export const ACTION_KEY ={
    GETPETS:"GETPETS",
    GET_SCHEDULE_EVENTS:'GET_SCHEDULE_EVENTS',
    POST_SCHEDULE_EVENTS:'POST_SCHEDULE_EVENTS'
};
export const ENDPOINTS = {
    PETSTORE: 'PetStore',
    CONSULT_API:'ConsultantApi'


};
export const API_ROUTE = {
    PETS: '/pets',
    SCHEDULE:'/schedule'

};
export const ACTION_ATTR ={
    PAYLOAD:'payload',
    DATA:'data'
};
