
const BACKEND_URL = 'http://18.196.118.163:8080/nxtbase';
export const REDUX_ACTIONS = {
    //saga action
    FETCHING:'FETCHING',
    FETCH_LATEST:'FETCH_LATEST',
    FETCHING_SUCCESS : 'FETCHING_SUCCESS',
    FETCHING_FAILURE:'FETCHING_FAILURE',
    //tutor redux action

    //user redux action
    GET_ALL_USERS_SUCCESS: "GET_ALL_USERS_SUCCESS",
    GET_ALL_USERS_FAILURE: "GET_ALL_USERS_FAILURE",
    CREATE_USER_SUCCESS:'CREATE_USER_SUCCESS',
    CREATE_USER_FAILURE:'CREATE_USER_FAILURE',
    DELETE_USER_SUCCESS:'DELETE_USER_SUCCESS',
    DELETE_USER_FAILURE:'DELETE_USER_FAILURE',
    UPDATE_USER_FAILURE:'UPDATE_USER_FAILURE',
    UPDATE_USER_SUCCESS:'UPDATE_USER_SUCCESS',
    EDITING_USER:'EDITING_USER',
    CREATED_USER:'CREATED_USER',

    //code group redux action
    GET_ALL_CODE_GROUPS_SUCCESS: "GET_ALL_CODE_GROUPS_SUCCESS",
    GET_ALL_CODE_GROUPS_FAILURE: "GET_ALL_CODE_GROUPS_FAILURE",
    CREATE_CODE_GROUP_SUCCESS:'CREATE_CODE_GROUP_SUCCESS',
    CREATE_CODE_GROUP_FAILURE:'CREATE_CODE_GROUP_FAILURE',
    DELETE_CODE_GROUP_SUCCESS:'DELETE_CODE_GROUP_SUCCESS',
    DELETE_CODE_GROUP_FAILURE:'DELETE_CODE_GROUP_FAILURE',
    UPDATE_CODE_GROUP_FAILURE:'UPDATE_CODE_GROUP_FAILURE',
    UPDATE_CODE_GROUP_SUCCESS:'UPDATE_CODE_GROUP_SUCCESS',
    EDITING_CODE_GROUP:'EDITING_CODE_GROUP',
    CREATED_CODE_GROUP:'CREATED_CODE_GROUP',


    //code record redux action
    GET_ALL_CODES_SUCCESS: "GET_ALL_CODES_SUCCESS",
    GET_ALL_CODES_FAILURE: "GET_ALL_CODES_FAILURE",
    CREATE_CODE_SUCCESS:'CREATE_CODE_SUCCESS',
    CREATE_CODE_FAILURE:'CREATE_CODE_FAILURE',
    DELETE_CODE_SUCCESS:'DELETE_CODE_SUCCESS',
    DELETE_CODE_FAILURE:'DELETE_CODE_FAILURE',
    UPDATE_CODE_FAILURE:'UPDATE_CODE_FAILURE',
    UPDATE_CODE_SUCCESS:'UPDATE_CODE_SUCCESS',
    EDITING_CODE:'EDITING_CODE',
    CREATED_CODE:'CREATED_CODE',

    //inspection plan record redux action
    GET_ALL_INSPECTION_PLANS_SUCCESS: "GET_ALL_INSPECTION_PLANS_SUCCESS",
    GET_ALL_INSPECTION_PLANS_FAILURE: "GET_ALL_INSPECTION_PLANS_FAILURE",
    CREATE_INSPECTION_PLAN_SUCCESS:'CREATE_INSPECTION_PLAN_SUCCESS',
    CREATE_INSPECTION_PLAN_FAILURE:'CREATE_INSPECTION_PLAN_FAILURE',
    DELETE_INSPECTION_PLAN_SUCCESS:'DELETE_INSPECTION_PLAN_SUCCESS',
    DELETE_INSPECTION_PLAN_FAILURE:'DELETE_INSPECTION_PLAN_FAILURE',
    UPDATE_INSPECTION_PLAN_FAILURE:'UPDATE_INSPECTION_PLAN_FAILURE',
    UPDATE_INSPECTION_PLAN_SUCCESS:'UPDATE_INSPECTION_PLAN_SUCCESS',
    EDITING_INSPECTION_PLAN:'EDITING_INSPECTION_PLAN',
    CREATED_INSPECTION_PLAN:'CREATED_INSPECTION_PLAN',

    //inspection item record redux action
    GET_ALL_INSPECTION_ITEMS_SUCCESS: "GET_ALL_INSPECTION_ITEMS_SUCCESS",
    GET_ALL_INSPECTION_ITEMS_FAILURE: "GET_ALL_INSPECTION_ITEMS_FAILURE",
    CREATE_INSPECTION_ITEM_SUCCESS:'CREATE_INSPECTION_ITEM_SUCCESS',
    CREATE_INSPECTION_ITEM_FAILURE:'CREATE_INSPECTION_ITEM_FAILURE',
    DELETE_INSPECTION_ITEM_SUCCESS:'DELETE_INSPECTION_ITEM_SUCCESS',
    DELETE_INSPECTION_ITEM_FAILURE:'DELETE_INSPECTION_ITEM_FAILURE',
    UPDATE_INSPECTION_ITEM_FAILURE:'UPDATE_INSPECTION_ITEM_FAILURE',
    UPDATE_INSPECTION_ITEM_SUCCESS:'UPDATE_INSPECTION_ITEM_SUCCESS',
    EDITING_INSPECTION_ITEM:'EDITING_INSPECTION_ITEM',
    CREATED_INSPECTION_ITEM:'CREATED_INSPECTION_ITEM',

    //inspection item problem code record redux action
    GET_ALL_INSPECTION_ITEM_PROBLEM_CODES_SUCCESS: "GET_ALL_INSPECTION_ITEM_PROBLEM_CODES_SUCCESS",
    GET_ALL_INSPECTION_ITEM_PROBLEM_CODES_FAILURE: "GET_ALL_INSPECTION_ITEM_PROBLEM_CODES_FAILURE",
    CREATE_INSPECTION_ITEM_PROBLEM_CODE_SUCCESS:'CREATE_INSPECTION_ITEM_PROBLEM_CODE_SUCCESS',
    CREATE_INSPECTION_ITEM_PROBLEM_CODE_FAILURE:'CREATE_INSPECTION_ITEM_PROBLEM_CODE_FAILURE',
    DELETE_INSPECTION_ITEM_PROBLEM_CODE_SUCCESS:'DELETE_INSPECTION_ITEM_PROBLEM_CODE_SUCCESS',
    DELETE_INSPECTION_ITEM_PROBLEM_CODE_FAILURE:'DELETE_INSPECTION_ITEM_PROBLEM_CODE_FAILURE',
    UPDATE_INSPECTION_ITEM_PROBLEM_CODE_FAILURE:'UPDATE_INSPECTION_ITEM_PROBLEM_CODE_FAILURE',
    UPDATE_INSPECTION_ITEM_PROBLEM_CODE_SUCCESS:'UPDATE_INSPECTION_ITEM_PROBLEM_CODE_SUCCESS',
    EDITING_INSPECTION_ITEM_PROBLEM_CODE:'EDITING_INSPECTION_ITEM_PROBLEM_CODE',
    CREATED_INSPECTION_ITEM_PROBLEM_CODE:'CREATED_INSPECTION_ITEM_PROBLEM_CODE',
    GET_PROBLEM_CODES_SUCCESS:'GET_PROBLEM_CODES_SUCCESS',
    GET_PROBLEM_CODES_FAILURE:'GET_PROBLEM_CODES_FAILURE',



    //inspection item reason code record redux action
    GET_ALL_INSPECTION_ITEM_REASON_CODES_SUCCESS: "GET_ALL_INSPECTION_ITEM_REASON_CODES_SUCCESS",
    GET_ALL_INSPECTION_ITEM_REASON_CODES_FAILURE: "GET_ALL_INSPECTION_ITEM_REASON_CODES_FAILURE",
    CREATE_INSPECTION_ITEM_REASON_CODE_SUCCESS:'CREATE_INSPECTION_ITEM_REASON_CODE_SUCCESS',
    CREATE_INSPECTION_ITEM_REASON_CODE_FAILURE:'CREATE_INSPECTION_ITEM_REASON_CODE_FAILURE',
    DELETE_INSPECTION_ITEM_REASON_CODE_SUCCESS:'DELETE_INSPECTION_ITEM_REASON_CODE_SUCCESS',
    DELETE_INSPECTION_ITEM_REASON_CODE_FAILURE:'DELETE_INSPECTION_ITEM_REASON_CODE_FAILURE',
    UPDATE_INSPECTION_ITEM_REASON_CODE_FAILURE:'UPDATE_INSPECTION_ITEM_REASON_CODE_FAILURE',
    UPDATE_INSPECTION_ITEM_REASON_CODE_SUCCESS:'UPDATE_INSPECTION_ITEM_REASON_CODE_SUCCESS',
    EDITING_INSPECTION_ITEM_REASON_CODE:'EDITING_INSPECTION_ITEM_REASON_CODE',
    CREATED_INSPECTION_ITEM_REASON_CODE:'CREATED_INSPECTION_ITEM_REASON_CODE',
    GET_REASON_CODES_SUCCESS:'GET_REASON_CODES_SUCCESS',
    GET_REASON_CODES_FAILURE:'GET_REASON_CODES_FAILURE',

}
export const USER_PROFILE ={
    UPDATE_FIRST_NAME:'UPDATE_FIRST_NAME',
    UPDATE_LAST_NAME:'UPDATE_LAST_NAME',
    UPDATE_EMAIL:'UPDATE_EMAIL',
    UPDATE_IMAGE:'UPDATE_IMAGE',
    UPDATE_ADDRESS:'UPDATE_ADDRESS',
    UPDATE_SCHOOL:'UPDATE_SCHOOL',
    UPDATE_DISTRICT:'UPDATE_DISTRICT',
    UPDATE_STREAM:'UPDATE_STREAM',
    UPDATE_SUBJECT:'UPDATE_SUBJECT'
}


export const ACTION_KEY ={

    //Users
    GET_ALL_USERS:"GET_ALL_USERS",
    CREATE_USER:"CREATE_USER",
    DELETE_USER:"DELETE_USER",
    UPDATE_USER:'UPDATE_USER',



    //Code Groups
    GET_ALL_CODE_GROUPS:'GET_ALL_CODE_GROUPS',
    CREATE_CODE_GROUP:'CREATE_CODE_GROUP',
    DELETE_CODE_GROUP:'DELETE_CODE_GROUP',
    UPDATE_CODE_GROUP:'UPDATE_CODE_GROUP',

    //Code Records
    GET_ALL_CODES:'GET_ALL_CODES',
    CREATE_CODE:'CREATE_CODE',
    DELETE_CODE:'DELETE_CODE',
    UPDATE_CODE:'UPDATE_CODE',

    //inspection plan Records
    GET_ALL_INSPECTION_PLANS:'GET_ALL_INSPECTION_PLANS',
    CREATE_INSPECTION_PLAN:'CREATE_INSPECTION_PLAN',
    DELETE_INSPECTION_PLAN:'DELETE_INSPECTION_PLAN',
    UPDATE_INSPECTION_PLAN:'UPDATE_INSPECTION_PLAN',

    //inspection item Records
    GET_ALL_INSPECTION_ITEMS:'GET_ALL_INSPECTION_ITEMS',
    CREATE_INSPECTION_ITEM:'CREATE_INSPECTION_ITEM',
    DELETE_INSPECTION_ITEM:'DELETE_INSPECTION_ITEM',
    UPDATE_INSPECTION_ITEM:'UPDATE_INSPECTION_ITEM',

    //inspection item problem code Records
    GET_ALL_INSPECTION_ITEM_PROBLEM_CODES:'GET_ALL_INSPECTION_ITEM_PROBLEM_CODES',
    CREATE_INSPECTION_ITEM_PROBLEM_CODE:'CREATE_INSPECTION_ITEM_PROBLEM_CODE',
    DELETE_INSPECTION_ITEM_PROBLEM_CODE:'DELETE_INSPECTION_ITEM_PROBLEM_CODE',
    UPDATE_INSPECTION_ITEM_PROBLEM_CODE:'UPDATE_INSPECTION_ITEM_PROBLEM_CODE',
    GET_PROBLEM_CODE:'GET_PROBLEM_CODE',


    //inspection item reason code Records
    GET_ALL_INSPECTION_ITEM_REASON_CODES:'GET_ALL_INSPECTION_ITEM_REASON_CODES',
    CREATE_INSPECTION_ITEM_REASON_CODE:'CREATE_INSPECTION_ITEM_REASON_CODE',
    DELETE_INSPECTION_ITEM_REASON_CODE:'DELETE_INSPECTION_ITEM_REASON_CODE',
    UPDATE_INSPECTION_ITEM_REASON_CODE:'UPDATE_INSPECTION_ITEM_REASON_CODE',
    GET_REASON_CODE:'GET_REASON_CODE',
}

export const ACTION_ATTR ={
    PAYLOAD:'payload',
    DATA:'data'
}
export const URLS = {
    //user
    GET_ALL_USERS: BACKEND_URL+'/nxtservice/users',
    CREATE_USER:BACKEND_URL+'/nxtservice/users',
    DELETE_USER:BACKEND_URL+'/nxtservice/users/:userId',
    UPDATE_USER:BACKEND_URL+'/nxtservice/users/:userId',


    //code group
    GET_ALL_CODE_GROUPS: BACKEND_URL+'/nxtservice/codegroups',
    CREATE_CODE_GROUP:BACKEND_URL+'/nxtservice/codegroups',
    DELETE_CODE_GROUP:BACKEND_URL+'/nxtservice/codegroups/:codeGroup',
    UPDATE_CODE_GROUP:BACKEND_URL+'/nxtservice/codegroups/:codeGroup',

    //code record
    GET_ALL_CODES: BACKEND_URL+'/nxtservice/codes',
    CREATE_CODE:BACKEND_URL+'/nxtservice/codes',
    DELETE_CODE:BACKEND_URL+'/nxtservice/codes/:code',
    UPDATE_CODE:BACKEND_URL+'/nxtservice/codes/:code',

    //inspection
    GET_ALL_INSPECTION_PLANS:BACKEND_URL+'/nxtservice/inspectionplans',
    CREATE_INSPECTION_PLAN:BACKEND_URL+'/nxtservice/inspectionplans',
    DELETE_INSPECTION_PLAN:BACKEND_URL+'/nxtservice/inspectionplans/:inspectionPlan',
    UPDATE_INSPECTION_PLAN:BACKEND_URL+'/nxtservice/inspectionplans/:inspectionPlan',

    //inspection item
    GET_ALL_INSPECTION_ITEMS:BACKEND_URL+'/nxtservice/inspectionitems/:inspectionPlan',
    CREATE_INSPECTION_ITEM:BACKEND_URL+'/nxtservice/inspectionitems',
    DELETE_INSPECTION_ITEM:BACKEND_URL+'/nxtservice/inspectionitems/:inspectionSubItem/:inspectionPlan',
    UPDATE_INSPECTION_ITEM:BACKEND_URL+'/nxtservice/inspectionitems/:inspectionSubItem/:inspectionPlan',

    //inspection item problem code
    GET_ALL_INSPECTION_ITEM_PROBLEM_CODES:BACKEND_URL+'/nxtservice/inspectionitemcodes/p/:inspectionPlan/:inspectionSubItem',
    CREATE_INSPECTION_ITEM_PROBLEM_CODE:BACKEND_URL+'/nxtservice/inspectionitemcodes',
    DELETE_INSPECTION_ITEM_PROBLEM_CODE:BACKEND_URL+'/nxtservice/inspectionitemcodes/:inspectionPlan/:inspectionSubItem/:code',
    UPDATE_INSPECTION_ITEM_PROBLEM_CODE:BACKEND_URL+'/nxtservice/inspectionitemcodes/:inspectionSubItem/:inspectionPlan',
    GET_PROBLEM_CODE:BACKEND_URL+'/nxtservice/problemcodes',

    //inspection item reason code
    GET_ALL_INSPECTION_ITEM_REASON_CODES:BACKEND_URL+'/nxtservice/inspectionitemcodes/r/:inspectionPlan/:inspectionSubItem',
    CREATE_INSPECTION_ITEM_REASON_CODE:BACKEND_URL+'/nxtservice/inspectionitemcodes',
    DELETE_INSPECTION_ITEM_REASON_CODE:BACKEND_URL+'/nxtservice/inspectionitemcodes/:inspectionPlan/:inspectionSubItem/:code',
    UPDATE_INSPECTION_ITEM_REASON_CODE:BACKEND_URL+'/nxtservice/inspectionitemcodes/:inspectionSubItem/:inspectionPlan',
    GET_REASON_CODE:BACKEND_URL+'/nxtservice/reasoncodes',
    
    
};
export const HTTP_METHODS = {
    GET: "GET",
    POST: "POST",
    DELETE: "DELETE",
    PUT:'PUT',
};
export const FETCH_KEYS = {
    MERCHANT_ID: 'merchantId',
    REGISTER_NO: 'registerNo',
    MAC_ADDRESS: 'macAddress'
};

export const HTTP_CODES = {
    SUCCESS: 200,
    CREATED:201,
    INTERNAL_ERROR: 500,
    BAD_REQUEST: 400,
    NOT_AUTHENTICATED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404
};
export const TIMEOUTS = {
    AUTH_REDIRECT: 1000,
    LOCAL_PROXY_SEND_RETRY: 1000,
    SECOND_IN_MILLIS: 1000
};

export const ROLE={
    ADMIN:0,
    CONSULTANT:1,
    CONSULTEE:2,


}