
const BACKEND_URL = 'http://18.196.118.163:8080/nxtbase';
export const REDUX_ACTIONS = {
    //saga action
    FETCHING:'FETCHING',
    FETCH_LATEST:'FETCH_LATEST',
    FETCHING_SUCCESS : 'FETCHING_SUCCESS',
    FETCHING_FAILURE:'FETCHING_FAILURE',
    //tutor redux action

    //user redux action
    GET_ALL_USERS_SUCCESS: "GET_ALL_USERS_SUCCESS",
    GET_ALL_USERS_FAILURE: "GET_ALL_USERS_FAILURE",
    CREATE_USER_SUCCESS:'CREATE_USER_SUCCESS',
    CREATE_USER_FAILURE:'CREATE_USER_FAILURE',
    DELETE_USER_SUCCESS:'DELETE_USER_SUCCESS',
    DELETE_USER_FAILURE:'DELETE_USER_FAILURE',
    UPDATE_USER_FAILURE:'UPDATE_USER_FAILURE',
    UPDATE_USER_SUCCESS:'UPDATE_USER_SUCCESS',
    EDITING_USER:'EDITING_USER',
    CREATED_USER:'CREATED_USER',

    //code group redux action
    GET_ALL_CODE_GROUPS_SUCCESS: "GET_ALL_CODE_GROUPS_SUCCESS",
    GET_ALL_CODE_GROUPS_FAILURE: "GET_ALL_CODE_GROUPS_FAILURE",
    CREATE_CODE_GROUP_SUCCESS:'CREATE_CODE_GROUP_SUCCESS',
    CREATE_CODE_GROUP_FAILURE:'CREATE_CODE_GROUP_FAILURE',
    DELETE_CODE_GROUP_SUCCESS:'DELETE_CODE_GROUP_SUCCESS',
    DELETE_CODE_GROUP_FAILURE:'DELETE_CODE_GROUP_FAILURE',
    UPDATE_CODE_GROUP_FAILURE:'UPDATE_CODE_GROUP_FAILURE',
    UPDATE_CODE_GROUP_SUCCESS:'UPDATE_CODE_GROUP_SUCCESS',
    EDITING_CODE_GROUP:'EDITING_CODE_GROUP',
    CREATED_CODE_GROUP:'CREATED_CODE_GROUP',


    //code record redux action
    GET_ALL_CODES_SUCCESS: "GET_ALL_CODES_SUCCESS",
    GET_ALL_CODES_FAILURE: "GET_ALL_CODES_FAILURE",
    CREATE_CODE_SUCCESS:'CREATE_CODE_SUCCESS',
    CREATE_CODE_FAILURE:'CREATE_CODE_FAILURE',
    DELETE_CODE_SUCCESS:'DELETE_CODE_SUCCESS',
    DELETE_CODE_FAILURE:'DELETE_CODE_FAILURE',
    UPDATE_CODE_FAILURE:'UPDATE_CODE_FAILURE',
    UPDATE_CODE_SUCCESS:'UPDATE_CODE_SUCCESS',
    EDITING_CODE:'EDITING_CODE',
    CREATED_CODE:'CREATED_CODE',

    //code record redux action
    GET_ALL_INSPECTION_PLANS_SUCCESS: "GET_ALL_INSPECTION_PLANS_SUCCESS",
    GET_ALL_INSPECTION_PLANS_FAILURE: "GET_ALL_INSPECTION_PLANS_FAILURE",
    CREATE_INSPECTION_PLAN_SUCCESS:'CREATE_INSPECTION_PLAN_SUCCESS',
    CREATE_INSPECTION_PLAN_FAILURE:'CREATE_INSPECTION_PLAN_FAILURE',
    DELETE_INSPECTION_PLAN_SUCCESS:'DELETE_INSPECTION_PLAN_SUCCESS',
    DELETE_INSPECTION_PLAN_FAILURE:'DELETE_INSPECTION_PLAN_FAILURE',
    UPDATE_INSPECTION_PLAN_FAILURE:'UPDATE_INSPECTION_PLAN_FAILURE',
    UPDATE_INSPECTION_PLAN_SUCCESS:'UPDATE_INSPECTION_PLAN_SUCCESS',
    EDITING_INSPECTION_PLAN:'EDITING_INSPECTION_PLAN',
    CREATED_INSPECTION_PLAN:'CREATED_INSPECTION_PLAN',



}
export const USER_PROFILE ={
    UPDATE_FIRST_NAME:'UPDATE_FIRST_NAME',
    UPDATE_LAST_NAME:'UPDATE_LAST_NAME',
    UPDATE_EMAIL:'UPDATE_EMAIL',
    UPDATE_IMAGE:'UPDATE_IMAGE',
    UPDATE_ADDRESS:'UPDATE_ADDRESS',
    UPDATE_SCHOOL:'UPDATE_SCHOOL',
    UPDATE_DISTRICT:'UPDATE_DISTRICT',
    UPDATE_STREAM:'UPDATE_STREAM',
    UPDATE_SUBJECT:'UPDATE_SUBJECT'
}


export const ACTION_KEY ={

    //Users
    GET_ALL_USERS:"GET_ALL_USERS",
    CREATE_USER:"CREATE_USER",
    DELETE_USER:"DELETE_USER",
    UPDATE_USER:'UPDATE_USER',



    //Code Groups
    GET_ALL_CODE_GROUPS:'GET_ALL_CODE_GROUPS',
    CREATE_CODE_GROUP:'CREATE_CODE_GROUP',
    DELETE_CODE_GROUP:'DELETE_CODE_GROUP',
    UPDATE_CODE_GROUP:'UPDATE_CODE_GROUP',

    //Code Records
    GET_ALL_CODES:'GET_ALL_CODES',
    CREATE_CODE:'CREATE_CODE',
    DELETE_CODE:'DELETE_CODE',
    UPDATE_CODE:'UPDATE_CODE',

    //inspection plan Records
    GET_ALL_INSPECTION_PLANS:'GET_ALL_INSPECTION_PLANS',
    CREATE_INSPECTION_PLAN:'CREATE_INSPECTION_PLAN',
    DELETE_INSPECTION_PLAN:'DELETE_INSPECTION_PLAN',
    UPDATE_INSPECTION_PLAN:'UPDATE_INSPECTION_PLAN',


}

export const ACTION_ATTR ={
    PAYLOAD:'payload',
    DATA:'data'
}
export const URLS = {
    //user
    GET_ALL_USERS: BACKEND_URL+'/nxtservice/users',
    CREATE_USER:BACKEND_URL+'/nxtservice/users',
    DELETE_USER:BACKEND_URL+'/nxtservice/users/:userId',
    UPDATE_USER:BACKEND_URL+'/nxtservice/users/:userId',


    //code group
    GET_ALL_CODE_GROUPS: BACKEND_URL+'/nxtservice/codegroups',
    CREATE_CODE_GROUP:BACKEND_URL+'/nxtservice/codegroups',
    DELETE_CODE_GROUP:BACKEND_URL+'/nxtservice/codegroups/:codeGroup',
    UPDATE_CODE_GROUP:BACKEND_URL+'/nxtservice/codegroups/:codeGroup',

    //code record
    GET_ALL_CODES: BACKEND_URL+'/nxtservice/codes',
    CREATE_CODE:BACKEND_URL+'/nxtservice/codes',
    DELETE_CODE:BACKEND_URL+'/nxtservice/codes/:code',
    UPDATE_CODE:BACKEND_URL+'/nxtservice/codes/:code',

    //inspection
    GET_ALL_INSPECTION_PLANS:BACKEND_URL+'/nxtservice/inspectionplans',
    CREATE_INSPECTION_PLAN:BACKEND_URL+'/nxtservice/inspectionplans',
    DELETE_INSPECTION_PLAN:BACKEND_URL+'/nxtservice/inspectionplans/:inspectionPlan',
    UPDATE_INSPECTION_PLAN:BACKEND_URL+'/nxtservice/inspectionplans/:inspectionPlan',
};
export const HTTP_METHODS = {
    GET: "GET",
    POST: "POST",
    DELETE: "DELETE",
    PUT:'PUT'
};
export const FETCH_KEYS = {
    MERCHANT_ID: 'merchantId',
    REGISTER_NO: 'registerNo',
    MAC_ADDRESS: 'macAddress'
};

export const HTTP_CODES = {
    SUCCESS: 200,
    CREATED:201,
    INTERNAL_ERROR: 500,
    BAD_REQUEST: 400,
    NOT_AUTHENTICATED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404
};
export const TIMEOUTS = {
    AUTH_REDIRECT: 1000,
    LOCAL_PROXY_SEND_RETRY: 1000,
    SECOND_IN_MILLIS: 1000
};

export const ROLE={
    ADMIN:0,
    CONSULTANT:1,
    CONSULTEE:2,


}